export const projectsData = [
    {
        "name": "buy_and_sell",
        "language": "Python3",
        "details": "Automated buy when DOGE dips and sell when it pumps with USDT. It uses Binance API to generate orders.",
        "link": "https://github.com/iam-agf/buy_and_sell.git"
    }, {
        "name": "controller_bot",
        "language": "Python3",
        "details": "Script that works as a daemon in your computer to use a telegram chat as a linux terminal only from your Telegram account. For now it only works for Linux",
        "link": "https://github.com/iam-agf/controller_bot.git"
    }, {
        "name": "GymApp",
        "language": "Dart/Flutter",
        "details": "Mobile app to trace your maximum Repetition Maximum using the Brzycki's Method. It has a set of exercise and has a chart to show the increment per registered day.",
        "link": "https://github.com/iam-agf/GymApp.git"
    }, {
        "name": "Send your ip",
        "language": "Python3",
        "details": "Script that works as a daemon in your pc to send your ip to your Telegram account",
        "link": "https://github.com/iam-agf/send-your-ip.git"
    }, {
        "name": "Kleinian groups",
        "language": "Python3",
        "details": "Scripts to visualize fractals generated by Kleinian groups. It's mainly based on the algorithms exposed in the book Indra's Pearls",
        "link": "https://github.com/iam-agf/kleinianGroups"
    }
]