export const projectsData = [
    {
        "name": "Asset Buy/Sell script",
        "language": "Python3",
        "details": "Script to automate buying DOGE assets when price dips and sell it for USDT when it pumps. It uses Binance API to generate orders.",
        "link": "https://github.com/iam-agf/buy_and_sell.git"
    }, {
        "name": "Telegram terminal Bot",
        "language": "Python3",
        "details": "Script that works as a daemon in your computer to use a telegram chat as a linux terminal from your Telegram account and will only answer to your messages. For now it only works for Linux.",
        "link": "https://github.com/iam-agf/controller_bot.git"
    }, {
        "name": "Simple React CV",
        "language": "Javascript/React/SCSS",
        "details": "This CV was written using React with SCSS.",
        "link": "https://github.com/iam-agf/react-cv"
    }, {
        "name": "App for Gym training",
        "language": "Dart/Flutter",
        "details": "Mobile app to trace your maximum Repetition Maximum using the Brzycki's Method. It has a set of exercise and a chart per exercise to show the increment registered per day.",
        "link": "https://github.com/iam-agf/GymApp.git"
    }, {
        "name": "Telegram IP sender Bot",
        "language": "Python3",
        "details": "Script that works as a daemon in your pc to send the ips of your computer to your Telegram account when it turns on.",
        "link": "https://github.com/iam-agf/send-your-ip.git"
    }, {
        "name": "Kleinian groups visualization",
        "language": "Python3",
        "details": "Scripts to visualize fractals generated by Kleinian groups. It's mainly based on the algorithms exposed in the book Indra's Pearls",
        "link": "https://github.com/iam-agf/kleinianGroups"
    }
]